[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_upload.flash_size = 4MB
board_build.partitions = huge_app.csv
build_flags =
  -DFASTLED_RMT_MAX_CHANNELS=1
upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
lib_deps =
    fastled/FastLED@^3.7.0
    bblanchon/ArduinoJson@^7.0.0
